### ISSUE TITLE
Unavailable forecast and historical data

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#93]
- What were you trying to achieve?
Accessing historical and forecast data using the API endpoints
- What are the expected results?
Receive the appropriate response messages as documented in our API
- What are the received results?
500 internal server errors
- What are the steps to reproduce the issue?
```

Access the endpoints using any REST client tool at your disposal, the endpoints in question are:
- https://data-manager-dot-airqo-250220.appspot.com/api/v1/data/feeds/hourly/912220
- https://ml-service-dot-airqo-250220.appspot.com/api/v1/predict

```
- In what environment did you encounter the issue?
```

- Mobile App (Android and IOS)
- REST client tools
- Web browsers

```

**Comment by Baalmart** [comment]
@sserurich 

Details of the error message received:

```
2020-07-11 06:49:55 ml-service[20200124t151455]  [2020-07-11 06:49:55,781] ERROR in app: 
Exception on /api/v1/predict/ [POST]
2020-07-11 06:49:55 ml-service[20200124t151455]  Traceback (most recent call last):    
File "/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app      
response = self.full_dispatch_request()    File "/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request      rv = self.handle_user_exception(e)    
File "/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception     
 reraise(exc_type, exc_value, tb)    File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, 
in reraise      raise value    File "/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request     
 rv = self.dispatch_request()    File "/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request  
    return self.view_functions[rule.endpoint](**req.view_args)    File "/home/vmagent/app/api/controller.py", line 120, in predict_avgs      entered_latitude,entered_longitude)    File "/home/vmagent/app/api/predict.py", line 103, in make_prediction_using_averages      yhat_24, lower_ci, upper_ci = simple_forecast_ci(data_to_use, 
best_number_of_days_back, considered_hours)    File "/home/vmagent/app/api/predict.py",
 line 251, in simple_forecast_ci      hourly_values = series[hours_to_count]  
IndexError: index -471 is out of bounds for axis 0 with size 470

```

**Comment by Baalmart** [comment]
Details of the error message received for the data-manager api endpoint:
`
the value for MONGO URL is: undefined`

**Comment by Baalmart** [comment]
One endpoint has been resolved,
Here: [GET] https://data-manager-dot-airqo-250220.uc.r.appspot.com/api/v1/data/feeds/hourly/912220
