### ISSUE TITLE
Runtime Issue in the data management service (node)

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#965]
**What were you trying to achieve?**
Just to retrieve the most recent device measurements using the data management API.

**What are the expected results?**
The API should return the expected values or an appropriate endpoint

**What are the received results?**

The Logs from the Cluster
```
Found 2 pods, using pod/airqo-stage-data-mgt-api-5b95cb7467-nnplt
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6915)
error:
{ response: { status: '404', error: 'Not Found' } }
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6917)
error:
{ response: { status: '404', error: 'Not Found' } }
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6919)
error:
{ response: { status: '404', error: 'Not Found' } }
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6921)
error:
{ response: { status: '404', error: 'Not Found' } }
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6923)
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6925)
error:
{ response: { status: '404', error: 'Not Found' } }
error:
{ response: { status: '404', error: 'Not Found' } }
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6927)
checking the date
the device is a BAM
transformedField: created_at
the device is a BAM
transformedField: date
the device is a BAM
transformedField: realtime_concetration
the device is a BAM
transformedField: hourly_concetration
the device is a BAM
transformedField: shorttime_concetration
the device is a BAM
transformedField: undefined
error:
{ config: undefined }
(node:32) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at Object.errorResponse (/usr/src/app/utils/errors.js:17:28)
    at /usr/src/app/controllers/transform.js:628:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6928)
```

**What are the steps to reproduce the issue?**
It is currently not possible to reproduce the issue right now which is unfortunate!

**In what environment did you encounter the issue?**
 - Postoman API client

**Additional context**
<img width="815" alt="Screenshot 2022-07-31 at 00 39 57" src="https://user-images.githubusercontent.com/1590213/182183480-b5f7b2eb-96f4-4445-a0c0-ccd198b8892a.png">
<img width="1082" alt="Screenshot 2022-07-31 at 00 41 27" src="https://user-images.githubusercontent.com/1590213/182183493-c5a53b67-5548-4fe6-b00e-057a03e21c49.png">
<img width="866" alt="Screenshot 2022-07-31 at 12 46 52" src="https://user-images.githubusercontent.com/1590213/182183966-2c32dfca-097a-4dcb-a03c-239a5ca21b45.png">

**Comment by Baalmart** [comment]
Hi @123MwanjeMike , please confirm if this issue still exists.

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike , please confirm if this issue still exists.

Not anymore @Baalmart
